name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Backend Job
  backend:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment for backend
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      # Install backend dependencies
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      # Run backend server (for development environment)
      - name: Run Backend
        working-directory: ./backend
        run: npm run dev
        env:
          MONGODB_URI: ${{ secrets.MONGO_URI }}  # MongoDB URI from GitHub Secrets
          JWT_SECRET: ${{ secrets.JWT_SECRET }}  # JWT Secret from GitHub Secrets

      - name: Deploy Backend to Render
        uses: render-examples/render-deploy@v1
        with:
          service: 'backend'
          render_token: ${{ secrets.RENDER_TOKEN_BACKEND }}  # Backend token from GitHub Secrets
        env:
          RENDER_API_TOKEN: ${{ secrets.RENDER_TOKEN_BACKEND }} 

  # Frontend Job
  frontend:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment for frontend
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      # Install frontend dependencies
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Set Backend URL for React
        run: echo "REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }}"

      # Run frontend server (for development environment)
      - name: Run Frontend
        working-directory: ./frontend
        run: npm start

      - name: Set Backend URL for React
        run: echo "REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }}"

      - name: Deploy Frontend to Render
        uses: render-examples/render-deploy@v1
        with:
          service: 'frontend'
          render_token: ${{ secrets.RENDER_TOKEN_FRONTEND }}  # Frontend token from GitHub Secrets
        env:
          RENDER_API_TOKEN: ${{ secrets.RENDER_TOKEN_FRONTEND }}
